#!/usr/bin/env python

"""Generates the ``api_exceptions`` module, by reading exceptions
data from the ``_api_exceptions.txt`` definition file.

A list of known API error codes can be found here: http://fbdevwiki.com/wiki/Error_codes

.. TODO: Also generate a nicer documentation page, grouping exceptions etc.
"""
import sys

if __name__ == '__main__':
    import os
    input_file = os.path.join(os.path.dirname(__file__), '_api_exceptions.txt')
    output_file = os.path.join(os.path.dirname(__file__), 'api_exceptions.py')
    
    _lines = 0
    
    inf = open(input_file, 'r')
    outf = open(output_file, 'w')
    
    outf.write("'''Auto-generated API Exceptions definition module'''\n\n")
    outf.write("from django_fbcanvas.exceptions import OAuthException\n\n")
    
    for line in inf:
        if line.strip():
            _lines += 1
            ec,em,ed = line.split(None, 2)
            ec = int(ec)
            if em.startswith('API_EC_'):
                em = em[7:]
            ed = ed.strip()
            _em_camel = ''.join([p.title() for p in em.split('_')])
            
            outf.write("class %sError(OAuthException):\n" % _em_camel)
            outf.write('    """Autogenerated exception class for API error code %d"""' % ec + "\n")
            outf.write("    error_code = %d\n" % ec)
            outf.write("    error_id = \"%s\"\n" % em)
            outf.write("    error_description = %r\n" % ed)
            outf.write("\n")
    
    inf.close()
    outf.close()
    
    sys.stderr.write("Written %s. %d exceptions was created.\n" % (output_file, _lines))
