'''Auto-generated API Exceptions definition module'''

from django_fbcanvas.exceptions import OAuthException

class SuccessError(OAuthException):
    """Autogenerated exception class for API error code 0"""
    error_code = 0
    error_id = "SUCCESS"
    error_description = 'Success'

class UnknownError(OAuthException):
    """Autogenerated exception class for API error code 1"""
    error_code = 1
    error_id = "UNKNOWN"
    error_description = 'An unknown error occurred'

class ServiceError(OAuthException):
    """Autogenerated exception class for API error code 2"""
    error_code = 2
    error_id = "SERVICE"
    error_description = 'Service temporarily unavailable'

class MethodError(OAuthException):
    """Autogenerated exception class for API error code 3"""
    error_code = 3
    error_id = "METHOD"
    error_description = 'Unknown method'

class TooManyCallsError(OAuthException):
    """Autogenerated exception class for API error code 4"""
    error_code = 4
    error_id = "TOO_MANY_CALLS"
    error_description = 'Application request limit reached'

class BadIpError(OAuthException):
    """Autogenerated exception class for API error code 5"""
    error_code = 5
    error_id = "BAD_IP"
    error_description = 'Unauthorized source IP address'

class HostApiError(OAuthException):
    """Autogenerated exception class for API error code 6"""
    error_code = 6
    error_id = "HOST_API"
    error_description = 'This method must run on api.facebook.com'

class HostUpError(OAuthException):
    """Autogenerated exception class for API error code 7"""
    error_code = 7
    error_id = "HOST_UP"
    error_description = 'This method must run on api-video.facebook.com'

class SecureError(OAuthException):
    """Autogenerated exception class for API error code 8"""
    error_code = 8
    error_id = "SECURE"
    error_description = 'This method requires an HTTPS connection'

class RateError(OAuthException):
    """Autogenerated exception class for API error code 9"""
    error_code = 9
    error_id = "RATE"
    error_description = 'User is performing too many actions'

class PermissionDeniedError(OAuthException):
    """Autogenerated exception class for API error code 10"""
    error_code = 10
    error_id = "PERMISSION_DENIED"
    error_description = 'Application does not have permission for this action'

class DeprecatedError(OAuthException):
    """Autogenerated exception class for API error code 11"""
    error_code = 11
    error_id = "DEPRECATED"
    error_description = 'This method is deprecated'

class VersionError(OAuthException):
    """Autogenerated exception class for API error code 12"""
    error_code = 12
    error_id = "VERSION"
    error_description = 'This API version is deprecated'

class InternalFqlErrorError(OAuthException):
    """Autogenerated exception class for API error code 13"""
    error_code = 13
    error_id = "INTERNAL_FQL_ERROR"
    error_description = 'The underlying FQL query made by this API call has encountered an error. Please check that your parameters are correct.'

class HostPupError(OAuthException):
    """Autogenerated exception class for API error code 14"""
    error_code = 14
    error_id = "HOST_PUP"
    error_description = 'This method must run on api-photo.facebook.com'

class SessionSecretNotAllowedError(OAuthException):
    """Autogenerated exception class for API error code 15"""
    error_code = 15
    error_id = "SESSION_SECRET_NOT_ALLOWED"
    error_description = 'This method call must be signed with the application secret (You are probably calling a secure method using a session secret)'

class HostReadonlyError(OAuthException):
    """Autogenerated exception class for API error code 16"""
    error_code = 16
    error_id = "HOST_READONLY"
    error_description = 'This method cannot be run on this host, which only supports read-only calls'

class UserTooManyCallsError(OAuthException):
    """Autogenerated exception class for API error code 17"""
    error_code = 17
    error_id = "USER_TOO_MANY_CALLS"
    error_description = 'User request limit reached'

class RequestResourcesExceededError(OAuthException):
    """Autogenerated exception class for API error code 18"""
    error_code = 18
    error_id = "REQUEST_RESOURCES_EXCEEDED"
    error_description = 'This API call could not be completed due to resource limits'

class ParamError(OAuthException):
    """Autogenerated exception class for API error code 100"""
    error_code = 100
    error_id = "PARAM"
    error_description = 'Invalid parameter'

class ParamApiKeyError(OAuthException):
    """Autogenerated exception class for API error code 101"""
    error_code = 101
    error_id = "PARAM_API_KEY"
    error_description = 'Invalid API key'

class ParamSessionKeyError(OAuthException):
    """Autogenerated exception class for API error code 102"""
    error_code = 102
    error_id = "PARAM_SESSION_KEY"
    error_description = 'Session key invalid or no longer valid'

class ParamCallIdError(OAuthException):
    """Autogenerated exception class for API error code 103"""
    error_code = 103
    error_id = "PARAM_CALL_ID"
    error_description = 'Call_id must be greater than previous'

class ParamSignatureError(OAuthException):
    """Autogenerated exception class for API error code 104"""
    error_code = 104
    error_id = "PARAM_SIGNATURE"
    error_description = 'Incorrect signature'

class ParamTooManyError(OAuthException):
    """Autogenerated exception class for API error code 105"""
    error_code = 105
    error_id = "PARAM_TOO_MANY"
    error_description = 'The number of parameters exceeded the maximum for this operation'

class ParamUserIdError(OAuthException):
    """Autogenerated exception class for API error code 110"""
    error_code = 110
    error_id = "PARAM_USER_ID"
    error_description = 'Invalid user id'

class ParamUserFieldError(OAuthException):
    """Autogenerated exception class for API error code 111"""
    error_code = 111
    error_id = "PARAM_USER_FIELD"
    error_description = 'Invalid user info field'

class ParamSocialFieldError(OAuthException):
    """Autogenerated exception class for API error code 112"""
    error_code = 112
    error_id = "PARAM_SOCIAL_FIELD"
    error_description = 'Invalid user field'

class ParamEmailError(OAuthException):
    """Autogenerated exception class for API error code 113"""
    error_code = 113
    error_id = "PARAM_EMAIL"
    error_description = 'Invalid email'

class ParamUserIdListError(OAuthException):
    """Autogenerated exception class for API error code 114"""
    error_code = 114
    error_id = "PARAM_USER_ID_LIST"
    error_description = 'Invalid user ID list'

class ParamFieldListError(OAuthException):
    """Autogenerated exception class for API error code 115"""
    error_code = 115
    error_id = "PARAM_FIELD_LIST"
    error_description = 'Invalid field list'

class ParamAlbumIdError(OAuthException):
    """Autogenerated exception class for API error code 120"""
    error_code = 120
    error_id = "PARAM_ALBUM_ID"
    error_description = 'Invalid album id'

class ParamPhotoIdError(OAuthException):
    """Autogenerated exception class for API error code 121"""
    error_code = 121
    error_id = "PARAM_PHOTO_ID"
    error_description = 'Invalid photo id'

class ParamFeedPriorityError(OAuthException):
    """Autogenerated exception class for API error code 130"""
    error_code = 130
    error_id = "PARAM_FEED_PRIORITY"
    error_description = 'Invalid feed publication priority'

class ParamCategoryError(OAuthException):
    """Autogenerated exception class for API error code 140"""
    error_code = 140
    error_id = "PARAM_CATEGORY"
    error_description = 'Invalid category'

class ParamSubcategoryError(OAuthException):
    """Autogenerated exception class for API error code 141"""
    error_code = 141
    error_id = "PARAM_SUBCATEGORY"
    error_description = 'Invalid subcategory'

class ParamTitleError(OAuthException):
    """Autogenerated exception class for API error code 142"""
    error_code = 142
    error_id = "PARAM_TITLE"
    error_description = 'Invalid title'

class ParamDescriptionError(OAuthException):
    """Autogenerated exception class for API error code 143"""
    error_code = 143
    error_id = "PARAM_DESCRIPTION"
    error_description = 'Invalid description'

class ParamBadJsonError(OAuthException):
    """Autogenerated exception class for API error code 144"""
    error_code = 144
    error_id = "PARAM_BAD_JSON"
    error_description = 'Malformed JSON string'

class ParamBadEidError(OAuthException):
    """Autogenerated exception class for API error code 150"""
    error_code = 150
    error_id = "PARAM_BAD_EID"
    error_description = 'Invalid eid'

class ParamUnknownCityError(OAuthException):
    """Autogenerated exception class for API error code 151"""
    error_code = 151
    error_id = "PARAM_UNKNOWN_CITY"
    error_description = 'Unknown city'

class ParamBadPageTypeError(OAuthException):
    """Autogenerated exception class for API error code 152"""
    error_code = 152
    error_id = "PARAM_BAD_PAGE_TYPE"
    error_description = 'Invalid page type'

class ParamBadLocaleError(OAuthException):
    """Autogenerated exception class for API error code 170"""
    error_code = 170
    error_id = "PARAM_BAD_LOCALE"
    error_description = 'Invalid locale'

class ParamBlockedNotificationError(OAuthException):
    """Autogenerated exception class for API error code 180"""
    error_code = 180
    error_id = "PARAM_BLOCKED_NOTIFICATION"
    error_description = 'This notification was not delieved'

class ParamAccessTokenError(OAuthException):
    """Autogenerated exception class for API error code 190"""
    error_code = 190
    error_id = "PARAM_ACCESS_TOKEN"
    error_description = 'Invalid OAuth 2.0 Access Token'

class PermissionError(OAuthException):
    """Autogenerated exception class for API error code 200"""
    error_code = 200
    error_id = "PERMISSION"
    error_description = 'Permissions error'

class PermissionUserError(OAuthException):
    """Autogenerated exception class for API error code 210"""
    error_code = 210
    error_id = "PERMISSION_USER"
    error_description = 'User not visible'

class PermissionNoDevelopersError(OAuthException):
    """Autogenerated exception class for API error code 211"""
    error_code = 211
    error_id = "PERMISSION_NO_DEVELOPERS"
    error_description = 'Application has no developers.'

class PermissionOfflineAccessError(OAuthException):
    """Autogenerated exception class for API error code 212"""
    error_code = 212
    error_id = "PERMISSION_OFFLINE_ACCESS"
    error_description = 'Renewing a session offline requires the extended permission offline_access'

class PermissionAlbumError(OAuthException):
    """Autogenerated exception class for API error code 220"""
    error_code = 220
    error_id = "PERMISSION_ALBUM"
    error_description = 'Album or albums not visible'

class PermissionPhotoError(OAuthException):
    """Autogenerated exception class for API error code 221"""
    error_code = 221
    error_id = "PERMISSION_PHOTO"
    error_description = 'Photo not visible'

class PermissionMessageError(OAuthException):
    """Autogenerated exception class for API error code 230"""
    error_code = 230
    error_id = "PERMISSION_MESSAGE"
    error_description = 'Permissions disallow message to user'

class PermissionMarkupOtherUserError(OAuthException):
    """Autogenerated exception class for API error code 240"""
    error_code = 240
    error_id = "PERMISSION_MARKUP_OTHER_USER"
    error_description = 'Desktop applications cannot set FBML for other users'

class PermissionStatusUpdateError(OAuthException):
    """Autogenerated exception class for API error code 250"""
    error_code = 250
    error_id = "PERMISSION_STATUS_UPDATE"
    error_description = 'Updating status requires the extended permission status_update.'

class PermissionPhotoUploadError(OAuthException):
    """Autogenerated exception class for API error code 260"""
    error_code = 260
    error_id = "PERMISSION_PHOTO_UPLOAD"
    error_description = 'Modifying existing photos requires the extended permission photo_upload'

class PermissionVideoUploadError(OAuthException):
    """Autogenerated exception class for API error code 261"""
    error_code = 261
    error_id = "PERMISSION_VIDEO_UPLOAD"
    error_description = 'Modifying existing photos requires the extended permission photo_upload'

class PermissionSmsError(OAuthException):
    """Autogenerated exception class for API error code 270"""
    error_code = 270
    error_id = "PERMISSION_SMS"
    error_description = 'Permissions disallow sms to user.'

class PermissionCreateListingError(OAuthException):
    """Autogenerated exception class for API error code 280"""
    error_code = 280
    error_id = "PERMISSION_CREATE_LISTING"
    error_description = 'Creating and modifying listings requires the extended permission create_listing'

class PermissionCreateNoteError(OAuthException):
    """Autogenerated exception class for API error code 281"""
    error_code = 281
    error_id = "PERMISSION_CREATE_NOTE"
    error_description = 'Managing notes requires the extended permission create_note.'

class PermissionShareItemError(OAuthException):
    """Autogenerated exception class for API error code 282"""
    error_code = 282
    error_id = "PERMISSION_SHARE_ITEM"
    error_description = 'Managing shared items requires the extended permission share_item.'

class PermissionEventError(OAuthException):
    """Autogenerated exception class for API error code 290"""
    error_code = 290
    error_id = "PERMISSION_EVENT"
    error_description = 'Creating and modifying events requires the extended permission create_event'

class PermissionLargeFbmlTemplateError(OAuthException):
    """Autogenerated exception class for API error code 291"""
    error_code = 291
    error_id = "PERMISSION_LARGE_FBML_TEMPLATE"
    error_description = "FBML Template isn\\'t owned by your application."

class PermissionLivemessageError(OAuthException):
    """Autogenerated exception class for API error code 292"""
    error_code = 292
    error_id = "PERMISSION_LIVEMESSAGE"
    error_description = 'An application is only allowed to send LiveMessages to users who have accepted the TOS for that application.'

class PermissionXmppLoginError(OAuthException):
    """Autogenerated exception class for API error code 293"""
    error_code = 293
    error_id = "PERMISSION_XMPP_LOGIN"
    error_description = 'Logging in to chat requires the extended permission xmpp_login'

class PermissionAdsManagementError(OAuthException):
    """Autogenerated exception class for API error code 294"""
    error_code = 294
    error_id = "PERMISSION_ADS_MANAGEMENT"
    error_description = 'Managing advertisements requires the extended permission ads_management, and a participating API key'

class PermissionCreateEventError(OAuthException):
    """Autogenerated exception class for API error code 296"""
    error_code = 296
    error_id = "PERMISSION_CREATE_EVENT"
    error_description = 'Managing events requires the extended permission create_event'

class PermissionReadMailboxError(OAuthException):
    """Autogenerated exception class for API error code 298"""
    error_code = 298
    error_id = "PERMISSION_READ_MAILBOX"
    error_description = 'Reading mailbox messages requires the extended permission read_mailbox'

class PermissionRsvpEventError(OAuthException):
    """Autogenerated exception class for API error code 299"""
    error_code = 299
    error_id = "PERMISSION_RSVP_EVENT"
    error_description = 'RSVPing to events requires the extended permission create_rsvp'

class EditError(OAuthException):
    """Autogenerated exception class for API error code 300"""
    error_code = 300
    error_id = "EDIT"
    error_description = 'Edit failure'

class EditUserDataError(OAuthException):
    """Autogenerated exception class for API error code 310"""
    error_code = 310
    error_id = "EDIT_USER_DATA"
    error_description = 'User data edit failure'

class EditPhotoError(OAuthException):
    """Autogenerated exception class for API error code 320"""
    error_code = 320
    error_id = "EDIT_PHOTO"
    error_description = 'Photo edit failure'

class EditAlbumSizeError(OAuthException):
    """Autogenerated exception class for API error code 321"""
    error_code = 321
    error_id = "EDIT_ALBUM_SIZE"
    error_description = 'Album is full'

class EditPhotoTagSubjectError(OAuthException):
    """Autogenerated exception class for API error code 322"""
    error_code = 322
    error_id = "EDIT_PHOTO_TAG_SUBJECT"
    error_description = 'Invalid photo tag subject'

class EditPhotoTagPhotoError(OAuthException):
    """Autogenerated exception class for API error code 323"""
    error_code = 323
    error_id = "EDIT_PHOTO_TAG_PHOTO"
    error_description = 'Cannot tag photo already visible on Facebook'

class EditPhotoFileError(OAuthException):
    """Autogenerated exception class for API error code 324"""
    error_code = 324
    error_id = "EDIT_PHOTO_FILE"
    error_description = 'Missing or invalid image file'

class EditPhotoPendingLimitError(OAuthException):
    """Autogenerated exception class for API error code 325"""
    error_code = 325
    error_id = "EDIT_PHOTO_PENDING_LIMIT"
    error_description = 'Too many unapproved photos pending'

class EditPhotoTagLimitError(OAuthException):
    """Autogenerated exception class for API error code 326"""
    error_code = 326
    error_id = "EDIT_PHOTO_TAG_LIMIT"
    error_description = 'Too many photo tags pending'

class EditAlbumReorderPhotoNotInAlbumError(OAuthException):
    """Autogenerated exception class for API error code 327"""
    error_code = 327
    error_id = "EDIT_ALBUM_REORDER_PHOTO_NOT_IN_ALBUM"
    error_description = 'Input array contains a photo not in the album'

class EditAlbumReorderTooFewPhotosError(OAuthException):
    """Autogenerated exception class for API error code 328"""
    error_code = 328
    error_id = "EDIT_ALBUM_REORDER_TOO_FEW_PHOTOS"
    error_description = 'Input array has too few photos'

class MalformedMarkupError(OAuthException):
    """Autogenerated exception class for API error code 329"""
    error_code = 329
    error_id = "MALFORMED_MARKUP"
    error_description = "Template data must be a JSON-encoded dictionary, of the form {'key-1': 'value-1', 'key-2': 'value-2', ...}"

class EditMarkupError(OAuthException):
    """Autogenerated exception class for API error code 330"""
    error_code = 330
    error_id = "EDIT_MARKUP"
    error_description = 'Failed to set markup'

class EditFeedTooManyUserCallsError(OAuthException):
    """Autogenerated exception class for API error code 340"""
    error_code = 340
    error_id = "EDIT_FEED_TOO_MANY_USER_CALLS"
    error_description = 'Feed publication request limit reached'

class EditFeedTooManyUserActionCallsError(OAuthException):
    """Autogenerated exception class for API error code 341"""
    error_code = 341
    error_id = "EDIT_FEED_TOO_MANY_USER_ACTION_CALLS"
    error_description = 'Feed action request limit reached'

class EditFeedTitleLinkError(OAuthException):
    """Autogenerated exception class for API error code 342"""
    error_code = 342
    error_id = "EDIT_FEED_TITLE_LINK"
    error_description = 'Feed story title can have at most one href anchor'

class EditFeedTitleLengthError(OAuthException):
    """Autogenerated exception class for API error code 343"""
    error_code = 343
    error_id = "EDIT_FEED_TITLE_LENGTH"
    error_description = 'Feed story title is too long'

class EditFeedTitleNameError(OAuthException):
    """Autogenerated exception class for API error code 344"""
    error_code = 344
    error_id = "EDIT_FEED_TITLE_NAME"
    error_description = 'Feed story title can have at most one fb:userlink and must be of the user whose action is being reported'

class EditFeedTitleBlankError(OAuthException):
    """Autogenerated exception class for API error code 345"""
    error_code = 345
    error_id = "EDIT_FEED_TITLE_BLANK"
    error_description = 'Feed story title rendered as blank'

class EditFeedBodyLengthError(OAuthException):
    """Autogenerated exception class for API error code 346"""
    error_code = 346
    error_id = "EDIT_FEED_BODY_LENGTH"
    error_description = 'Feed story body is too long'

class EditFeedPhotoSrcError(OAuthException):
    """Autogenerated exception class for API error code 347"""
    error_code = 347
    error_id = "EDIT_FEED_PHOTO_SRC"
    error_description = 'Feed story photo could not be accessed or proxied'

class EditFeedPhotoLinkError(OAuthException):
    """Autogenerated exception class for API error code 348"""
    error_code = 348
    error_id = "EDIT_FEED_PHOTO_LINK"
    error_description = 'Feed story photo link invalid'

class EditVideoSizeError(OAuthException):
    """Autogenerated exception class for API error code 350"""
    error_code = 350
    error_id = "EDIT_VIDEO_SIZE"
    error_description = 'Video file is too large'

class EditVideoInvalidFileError(OAuthException):
    """Autogenerated exception class for API error code 351"""
    error_code = 351
    error_id = "EDIT_VIDEO_INVALID_FILE"
    error_description = 'Video file was corrupt or invalid'

class EditVideoInvalidTypeError(OAuthException):
    """Autogenerated exception class for API error code 352"""
    error_code = 352
    error_id = "EDIT_VIDEO_INVALID_TYPE"
    error_description = 'Video file format is not supported'

class EditVideoFileError(OAuthException):
    """Autogenerated exception class for API error code 353"""
    error_code = 353
    error_id = "EDIT_VIDEO_FILE"
    error_description = 'Missing video file'

class EditVideoNotTaggedError(OAuthException):
    """Autogenerated exception class for API error code 354"""
    error_code = 354
    error_id = "EDIT_VIDEO_NOT_TAGGED"
    error_description = 'User is not tagged in this video'

class EditVideoAlreadyTaggedError(OAuthException):
    """Autogenerated exception class for API error code 355"""
    error_code = 355
    error_id = "EDIT_VIDEO_ALREADY_TAGGED"
    error_description = 'User is already tagged in this video'

class EditFeedTitleArrayError(OAuthException):
    """Autogenerated exception class for API error code 360"""
    error_code = 360
    error_id = "EDIT_FEED_TITLE_ARRAY"
    error_description = 'Feed story title_data argument was not a valid JSON-encoded array'

class EditFeedTitleParamsError(OAuthException):
    """Autogenerated exception class for API error code 361"""
    error_code = 361
    error_id = "EDIT_FEED_TITLE_PARAMS"
    error_description = 'Feed story title template either missing required parameters, or did not have all parameters defined in title_data array'

class EditFeedBodyArrayError(OAuthException):
    """Autogenerated exception class for API error code 362"""
    error_code = 362
    error_id = "EDIT_FEED_BODY_ARRAY"
    error_description = 'Feed story body_data argument was not a valid JSON-encoded array'

class EditFeedBodyParamsError(OAuthException):
    """Autogenerated exception class for API error code 363"""
    error_code = 363
    error_id = "EDIT_FEED_BODY_PARAMS"
    error_description = 'Feed story body template either missing required parameters, or did not have all parameters defined in body_data array'

class EditFeedPhotoError(OAuthException):
    """Autogenerated exception class for API error code 364"""
    error_code = 364
    error_id = "EDIT_FEED_PHOTO"
    error_description = 'Feed story photos could not be retrieved, or bad image links were provided'

class EditFeedTemplateError(OAuthException):
    """Autogenerated exception class for API error code 365"""
    error_code = 365
    error_id = "EDIT_FEED_TEMPLATE"
    error_description = 'The template for this story does not match any templates registered for this application'

class EditFeedTargetError(OAuthException):
    """Autogenerated exception class for API error code 366"""
    error_code = 366
    error_id = "EDIT_FEED_TARGET"
    error_description = 'One or more of the target ids for this story are invalid. They must all be ids of friends of the acting user'

class EditFeedMarkupError(OAuthException):
    """Autogenerated exception class for API error code 367"""
    error_code = 367
    error_id = "EDIT_FEED_MARKUP"
    error_description = "The template data provided doesn't cover the entire token set needed to publish the story"

class UsersCreateInvalidEmailError(OAuthException):
    """Autogenerated exception class for API error code 370"""
    error_code = 370
    error_id = "USERS_CREATE_INVALID_EMAIL"
    error_description = 'The email address you provided is not a valid email address'

class UsersCreateExistingEmailError(OAuthException):
    """Autogenerated exception class for API error code 371"""
    error_code = 371
    error_id = "USERS_CREATE_EXISTING_EMAIL"
    error_description = 'The email address you provided belongs to an existing account'

class UsersCreateBirthdayError(OAuthException):
    """Autogenerated exception class for API error code 372"""
    error_code = 372
    error_id = "USERS_CREATE_BIRTHDAY"
    error_description = 'The birthday provided is not valid'

class UsersCreatePasswordError(OAuthException):
    """Autogenerated exception class for API error code 373"""
    error_code = 373
    error_id = "USERS_CREATE_PASSWORD"
    error_description = 'The password provided is too short or weak'

class UsersRegisterInvalidCredentialError(OAuthException):
    """Autogenerated exception class for API error code 374"""
    error_code = 374
    error_id = "USERS_REGISTER_INVALID_CREDENTIAL"
    error_description = 'The login credential you provided is invalid.'

class UsersRegisterConfFailureError(OAuthException):
    """Autogenerated exception class for API error code 375"""
    error_code = 375
    error_id = "USERS_REGISTER_CONF_FAILURE"
    error_description = 'Failed to send confirmation message to the specified login credential.'

class UsersRegisterExistingError(OAuthException):
    """Autogenerated exception class for API error code 376"""
    error_code = 376
    error_id = "USERS_REGISTER_EXISTING"
    error_description = 'The login credential you provided belongs to an existing account'

class UsersRegisterDefaultErrorError(OAuthException):
    """Autogenerated exception class for API error code 377"""
    error_code = 377
    error_id = "USERS_REGISTER_DEFAULT_ERROR"
    error_description = 'Sorry, we were unable to process your registration.'

class UsersRegisterPasswordBlankError(OAuthException):
    """Autogenerated exception class for API error code 378"""
    error_code = 378
    error_id = "USERS_REGISTER_PASSWORD_BLANK"
    error_description = 'Your password cannot be blank. Please try another.'

class UsersRegisterPasswordInvalidCharsError(OAuthException):
    """Autogenerated exception class for API error code 379"""
    error_code = 379
    error_id = "USERS_REGISTER_PASSWORD_INVALID_CHARS"
    error_description = 'Your password contains invalid characters. Please try another.'

class UsersRegisterPasswordShortError(OAuthException):
    """Autogenerated exception class for API error code 380"""
    error_code = 380
    error_id = "USERS_REGISTER_PASSWORD_SHORT"
    error_description = 'Your password must be at least 6 characters long. Please try another.'

class UsersRegisterPasswordWeakError(OAuthException):
    """Autogenerated exception class for API error code 381"""
    error_code = 381
    error_id = "USERS_REGISTER_PASSWORD_WEAK"
    error_description = 'Your password should be more secure. Please try another.'

class UsersRegisterUsernameErrorError(OAuthException):
    """Autogenerated exception class for API error code 382"""
    error_code = 382
    error_id = "USERS_REGISTER_USERNAME_ERROR"
    error_description = 'Our automated system will not approve this name.'

class UsersRegisterMissingInputError(OAuthException):
    """Autogenerated exception class for API error code 383"""
    error_code = 383
    error_id = "USERS_REGISTER_MISSING_INPUT"
    error_description = 'You must fill in all of the fields.'

class UsersRegisterIncompleteBdayError(OAuthException):
    """Autogenerated exception class for API error code 384"""
    error_code = 384
    error_id = "USERS_REGISTER_INCOMPLETE_BDAY"
    error_description = 'You must indicate your full birthday to register.'

class UsersRegisterInvalidEmailError(OAuthException):
    """Autogenerated exception class for API error code 385"""
    error_code = 385
    error_id = "USERS_REGISTER_INVALID_EMAIL"
    error_description = 'Please enter a valid email address.'

class UsersRegisterEmailDisabledError(OAuthException):
    """Autogenerated exception class for API error code 386"""
    error_code = 386
    error_id = "USERS_REGISTER_EMAIL_DISABLED"
    error_description = 'The email address you entered has been disabled. Please contact disabled@facebook.com with any questions.'

class UsersRegisterAddUserFailedError(OAuthException):
    """Autogenerated exception class for API error code 387"""
    error_code = 387
    error_id = "USERS_REGISTER_ADD_USER_FAILED"
    error_description = 'There was an error with your registration. Please try registering again.'

class UsersRegisterNoGenderError(OAuthException):
    """Autogenerated exception class for API error code 388"""
    error_code = 388
    error_id = "USERS_REGISTER_NO_GENDER"
    error_description = 'Please select either Male or Female.'

class AuthEmailError(OAuthException):
    """Autogenerated exception class for API error code 400"""
    error_code = 400
    error_id = "AUTH_EMAIL"
    error_description = 'Invalid email address'

class AuthLoginError(OAuthException):
    """Autogenerated exception class for API error code 401"""
    error_code = 401
    error_id = "AUTH_LOGIN"
    error_description = 'Invalid username or password'

class AuthSigError(OAuthException):
    """Autogenerated exception class for API error code 402"""
    error_code = 402
    error_id = "AUTH_SIG"
    error_description = 'Invalid application auth sig'

class AuthTimeError(OAuthException):
    """Autogenerated exception class for API error code 403"""
    error_code = 403
    error_id = "AUTH_TIME"
    error_description = 'Invalid timestamp for authentication'

class SessionTimedOutError(OAuthException):
    """Autogenerated exception class for API error code 450"""
    error_code = 450
    error_id = "SESSION_TIMED_OUT"
    error_description = 'Session key specified has passed its expiration time'

class SessionMethodError(OAuthException):
    """Autogenerated exception class for API error code 451"""
    error_code = 451
    error_id = "SESSION_METHOD"
    error_description = 'Session key specified cannot be used to call this method'

class SessionInvalidError(OAuthException):
    """Autogenerated exception class for API error code 452"""
    error_code = 452
    error_id = "SESSION_INVALID"
    error_description = 'Session key invalid. This could be because the session key has an incorrect format, or because the user has revoked this session'

class SessionRequiredError(OAuthException):
    """Autogenerated exception class for API error code 453"""
    error_code = 453
    error_id = "SESSION_REQUIRED"
    error_description = 'A session key is required for calling this method'

class SessionRequiredForSecretError(OAuthException):
    """Autogenerated exception class for API error code 454"""
    error_code = 454
    error_id = "SESSION_REQUIRED_FOR_SECRET"
    error_description = 'A session key must be specified when request is signed with a session secret'

class SessionCannotUseSessionSecretError(OAuthException):
    """Autogenerated exception class for API error code 455"""
    error_code = 455
    error_id = "SESSION_CANNOT_USE_SESSION_SECRET"
    error_description = 'A session secret is not permitted to be used with this type of session key'

class MesgBannedError(OAuthException):
    """Autogenerated exception class for API error code 500"""
    error_code = 500
    error_id = "MESG_BANNED"
    error_description = 'Message contains banned content'

class MesgNoBodyError(OAuthException):
    """Autogenerated exception class for API error code 501"""
    error_code = 501
    error_id = "MESG_NO_BODY"
    error_description = 'Missing message body'

class MesgTooLongError(OAuthException):
    """Autogenerated exception class for API error code 502"""
    error_code = 502
    error_id = "MESG_TOO_LONG"
    error_description = 'Message is too long'

class MesgRateError(OAuthException):
    """Autogenerated exception class for API error code 503"""
    error_code = 503
    error_id = "MESG_RATE"
    error_description = 'User has sent too many messages'

class MesgInvalidThreadError(OAuthException):
    """Autogenerated exception class for API error code 504"""
    error_code = 504
    error_id = "MESG_INVALID_THREAD"
    error_description = 'Invalid reply thread id'

class MesgInvalidRecipError(OAuthException):
    """Autogenerated exception class for API error code 505"""
    error_code = 505
    error_id = "MESG_INVALID_RECIP"
    error_description = 'Invalid message recipient'

class PokeInvalidRecipError(OAuthException):
    """Autogenerated exception class for API error code 510"""
    error_code = 510
    error_id = "POKE_INVALID_RECIP"
    error_description = 'Invalid poke recipient'

class PokeOutstandingError(OAuthException):
    """Autogenerated exception class for API error code 511"""
    error_code = 511
    error_id = "POKE_OUTSTANDING"
    error_description = 'There is a poke already outstanding'

class PokeRateError(OAuthException):
    """Autogenerated exception class for API error code 512"""
    error_code = 512
    error_id = "POKE_RATE"
    error_description = 'User is poking too fast'

class PokeUserBlockedError(OAuthException):
    """Autogenerated exception class for API error code 513"""
    error_code = 513
    error_id = "POKE_USER_BLOCKED"
    error_description = 'User cannot poke via API'

class FqlEcUnknownErrorError(OAuthException):
    """Autogenerated exception class for API error code 600"""
    error_code = 600
    error_id = "FQL_EC_UNKNOWN_ERROR"
    error_description = 'An unknown error occurred in FQL'

class FqlEcParserErrorError(OAuthException):
    """Autogenerated exception class for API error code 601"""
    error_code = 601
    error_id = "FQL_EC_PARSER_ERROR"
    error_description = 'Error while parsing FQL statement'

class FqlEcUnknownFieldError(OAuthException):
    """Autogenerated exception class for API error code 602"""
    error_code = 602
    error_id = "FQL_EC_UNKNOWN_FIELD"
    error_description = 'The field you requested does not exist'

class FqlEcUnknownTableError(OAuthException):
    """Autogenerated exception class for API error code 603"""
    error_code = 603
    error_id = "FQL_EC_UNKNOWN_TABLE"
    error_description = 'The table you requested does not exist'

class FqlEcNoIndexError(OAuthException):
    """Autogenerated exception class for API error code 604"""
    error_code = 604
    error_id = "FQL_EC_NO_INDEX"
    error_description = 'Your statement is not indexable'

class FqlEcUnknownFunctionError(OAuthException):
    """Autogenerated exception class for API error code 605"""
    error_code = 605
    error_id = "FQL_EC_UNKNOWN_FUNCTION"
    error_description = 'The function you called does not exist'

class FqlEcInvalidParamError(OAuthException):
    """Autogenerated exception class for API error code 606"""
    error_code = 606
    error_id = "FQL_EC_INVALID_PARAM"
    error_description = 'Wrong number of arguments passed into the function'

class FqlEcInvalidFieldError(OAuthException):
    """Autogenerated exception class for API error code 607"""
    error_code = 607
    error_id = "FQL_EC_INVALID_FIELD"
    error_description = 'FQL field specified is invalid in this context.'

class FqlEcInvalidSessionError(OAuthException):
    """Autogenerated exception class for API error code 608"""
    error_code = 608
    error_id = "FQL_EC_INVALID_SESSION"
    error_description = 'An invalid session was specified'

class FqlEcUnsupportedAppTypeError(OAuthException):
    """Autogenerated exception class for API error code 609"""
    error_code = 609
    error_id = "FQL_EC_UNSUPPORTED_APP_TYPE"
    error_description = 'FQL field specified is invalid in this context.'

class FqlEcSessionSecretNotAllowedError(OAuthException):
    """Autogenerated exception class for API error code 610"""
    error_code = 610
    error_id = "FQL_EC_SESSION_SECRET_NOT_ALLOWED"
    error_description = 'FQL field specified is invalid in this context.'

class FqlEcDeprecatedTableError(OAuthException):
    """Autogenerated exception class for API error code 611"""
    error_code = 611
    error_id = "FQL_EC_DEPRECATED_TABLE"
    error_description = 'FQL field specified is invalid in this context.'

class FqlEcExtendedPermissionError(OAuthException):
    """Autogenerated exception class for API error code 612"""
    error_code = 612
    error_id = "FQL_EC_EXTENDED_PERMISSION"
    error_description = 'The stream requires an extended permission'

class FqlEcRateLimitExceededError(OAuthException):
    """Autogenerated exception class for API error code 613"""
    error_code = 613
    error_id = "FQL_EC_RATE_LIMIT_EXCEEDED"
    error_description = 'Calls to stream have exceeded the rate of 100 calls per 600 seconds.'

class FqlEcUnresolvedDependencyError(OAuthException):
    """Autogenerated exception class for API error code 614"""
    error_code = 614
    error_id = "FQL_EC_UNRESOLVED_DEPENDENCY"
    error_description = 'Unresolved dependency in multiquery'

class FqlEcInvalidSearchError(OAuthException):
    """Autogenerated exception class for API error code 615"""
    error_code = 615
    error_id = "FQL_EC_INVALID_SEARCH"
    error_description = 'This search is invalid'

class FqlEcTooManyFriendsForPreloadError(OAuthException):
    """Autogenerated exception class for API error code 617"""
    error_code = 617
    error_id = "FQL_EC_TOO_MANY_FRIENDS_FOR_PRELOAD"
    error_description = 'The user you queried against has too many friends to be used with Preload FQL, in order to avoid out of memory errors'

class RefSetFailedError(OAuthException):
    """Autogenerated exception class for API error code 700"""
    error_code = 700
    error_id = "REF_SET_FAILED"
    error_description = 'Unknown failure in storing ref data. Please try again.'

class FbAppUnknownErrorError(OAuthException):
    """Autogenerated exception class for API error code 750"""
    error_code = 750
    error_id = "FB_APP_UNKNOWN_ERROR"
    error_description = 'Unknown Facebook application integration failure.'

class FbAppFetchFailedError(OAuthException):
    """Autogenerated exception class for API error code 751"""
    error_code = 751
    error_id = "FB_APP_FETCH_FAILED"
    error_description = 'Fetch from remote site failed.'

class FbAppNoDataError(OAuthException):
    """Autogenerated exception class for API error code 752"""
    error_code = 752
    error_id = "FB_APP_NO_DATA"
    error_description = 'Application returned no data. This may be expected or represent a connectivity error.'

class FbAppNoPermissionsError(OAuthException):
    """Autogenerated exception class for API error code 753"""
    error_code = 753
    error_id = "FB_APP_NO_PERMISSIONS"
    error_description = 'Application returned user had invalid permissions to complete the operation.'

class FbAppTagMissingError(OAuthException):
    """Autogenerated exception class for API error code 754"""
    error_code = 754
    error_id = "FB_APP_TAG_MISSING"
    error_description = 'Application returned data, but no matching tag found. This may be expected.'

class FbAppDbFailureError(OAuthException):
    """Autogenerated exception class for API error code 755"""
    error_code = 755
    error_id = "FB_APP_DB_FAILURE"
    error_description = 'The database for this object failed.'

class DataUnknownErrorError(OAuthException):
    """Autogenerated exception class for API error code 800"""
    error_code = 800
    error_id = "DATA_UNKNOWN_ERROR"
    error_description = 'Unknown data store API error'

class DataInvalidOperationError(OAuthException):
    """Autogenerated exception class for API error code 801"""
    error_code = 801
    error_id = "DATA_INVALID_OPERATION"
    error_description = 'Invalid operation'

class DataQuotaExceededError(OAuthException):
    """Autogenerated exception class for API error code 802"""
    error_code = 802
    error_id = "DATA_QUOTA_EXCEEDED"
    error_description = 'Data store allowable quota was exceeded'

class DataObjectNotFoundError(OAuthException):
    """Autogenerated exception class for API error code 803"""
    error_code = 803
    error_id = "DATA_OBJECT_NOT_FOUND"
    error_description = 'Specified object cannot be found'

class DataObjectAlreadyExistsError(OAuthException):
    """Autogenerated exception class for API error code 804"""
    error_code = 804
    error_id = "DATA_OBJECT_ALREADY_EXISTS"
    error_description = 'Specified object already exists'

class DataDatabaseErrorError(OAuthException):
    """Autogenerated exception class for API error code 805"""
    error_code = 805
    error_id = "DATA_DATABASE_ERROR"
    error_description = 'A database error occurred. Please try again'

class DataCreateTemplateErrorError(OAuthException):
    """Autogenerated exception class for API error code 806"""
    error_code = 806
    error_id = "DATA_CREATE_TEMPLATE_ERROR"
    error_description = 'Unable to add FBML template to template database. Please try again.'

class DataTemplateExistsErrorError(OAuthException):
    """Autogenerated exception class for API error code 807"""
    error_code = 807
    error_id = "DATA_TEMPLATE_EXISTS_ERROR"
    error_description = 'No active template bundle with that ID or handle exists.'

class DataTemplateHandleTooLongError(OAuthException):
    """Autogenerated exception class for API error code 808"""
    error_code = 808
    error_id = "DATA_TEMPLATE_HANDLE_TOO_LONG"
    error_description = 'Template bundle handles must contain less than or equal to 32 characters.'

class DataTemplateHandleAlreadyInUseError(OAuthException):
    """Autogenerated exception class for API error code 809"""
    error_code = 809
    error_id = "DATA_TEMPLATE_HANDLE_ALREADY_IN_USE"
    error_description = 'Template bundle handle already identifies a previously registered template bundle, and handles can not be reused.'

class DataTooManyTemplateBundlesError(OAuthException):
    """Autogenerated exception class for API error code 810"""
    error_code = 810
    error_id = "DATA_TOO_MANY_TEMPLATE_BUNDLES"
    error_description = 'Application has too many active template bundles, and some must be deactivated before new ones can be registered.'

class DataMalformedActionLinkError(OAuthException):
    """Autogenerated exception class for API error code 811"""
    error_code = 811
    error_id = "DATA_MALFORMED_ACTION_LINK"
    error_description = 'One of more of the supplied action links was improperly formatted.'

class DataTemplateUsesReservedTokenError(OAuthException):
    """Autogenerated exception class for API error code 812"""
    error_code = 812
    error_id = "DATA_TEMPLATE_USES_RESERVED_TOKEN"
    error_description = 'One \xe2\x80\xa6or more of your templates is using a token reserved by Facebook, such as {*mp3*} or {*video*}.'

class SmsInvalidSessionError(OAuthException):
    """Autogenerated exception class for API error code 850"""
    error_code = 850
    error_id = "SMS_INVALID_SESSION"
    error_description = 'Invalid sms session.'

class SmsMsgLenError(OAuthException):
    """Autogenerated exception class for API error code 851"""
    error_code = 851
    error_id = "SMS_MSG_LEN"
    error_description = 'Invalid sms message length.'

class SmsUserQuotaError(OAuthException):
    """Autogenerated exception class for API error code 852"""
    error_code = 852
    error_id = "SMS_USER_QUOTA"
    error_description = 'Over user daily sms quota.'

class SmsUserAsleepError(OAuthException):
    """Autogenerated exception class for API error code 853"""
    error_code = 853
    error_id = "SMS_USER_ASLEEP"
    error_description = 'Unable to send sms to user at this time.'

class SmsAppQuotaError(OAuthException):
    """Autogenerated exception class for API error code 854"""
    error_code = 854
    error_id = "SMS_APP_QUOTA"
    error_description = 'Over application daily sms quota/rate limit.'

class SmsNotRegisteredError(OAuthException):
    """Autogenerated exception class for API error code 855"""
    error_code = 855
    error_id = "SMS_NOT_REGISTERED"
    error_description = 'User is not registered for Facebook Mobile Texts'

class SmsNotificationsOffError(OAuthException):
    """Autogenerated exception class for API error code 856"""
    error_code = 856
    error_id = "SMS_NOTIFICATIONS_OFF"
    error_description = 'User has SMS notifications turned off'

class SmsCarrierDisableError(OAuthException):
    """Autogenerated exception class for API error code 857"""
    error_code = 857
    error_id = "SMS_CARRIER_DISABLE"
    error_description = 'SMS application disallowed by mobile operator'

class NoSuchAppError(OAuthException):
    """Autogenerated exception class for API error code 900"""
    error_code = 900
    error_id = "NO_SUCH_APP"
    error_description = 'No such application exists.'

class ApiBatchTooManyItemsError(OAuthException):
    """Autogenerated exception class for API error code 950"""
    error_code = 950
    error_id = "API_BATCH_TOO_MANY_ITEMS"
    error_description = 'Each batch API can not contain more than 20 items'

class BatchAlreadyStartedError(OAuthException):
    """Autogenerated exception class for API error code 951"""
    error_code = 951
    error_id = "BATCH_ALREADY_STARTED"
    error_description = 'begin_batch already called, please make sure to call end_batch first.'

class BatchNotStartedError(OAuthException):
    """Autogenerated exception class for API error code 952"""
    error_code = 952
    error_id = "BATCH_NOT_STARTED"
    error_description = 'end_batch called before begin_batch.'

class BatchMethodNotAllowedInBatchModeError(OAuthException):
    """Autogenerated exception class for API error code 953"""
    error_code = 953
    error_id = "BATCH_METHOD_NOT_ALLOWED_IN_BATCH_MODE"
    error_description = 'This method is not allowed in batch mode.'

class EventInvalidTimeError(OAuthException):
    """Autogenerated exception class for API error code 1000"""
    error_code = 1000
    error_id = "EVENT_INVALID_TIME"
    error_description = 'Invalid time for an event.'

class EventNameLockedError(OAuthException):
    """Autogenerated exception class for API error code 1001"""
    error_code = 1001
    error_id = "EVENT_NAME_LOCKED"
    error_description = 'You are no longer able to change the name of this event.'

class InfoNoInformationError(OAuthException):
    """Autogenerated exception class for API error code 1050"""
    error_code = 1050
    error_id = "INFO_NO_INFORMATION"
    error_description = 'No information has been set for this user'

class InfoSetFailedError(OAuthException):
    """Autogenerated exception class for API error code 1051"""
    error_code = 1051
    error_id = "INFO_SET_FAILED"
    error_description = 'Setting info failed. Check the formatting of your info fields.'

class LivemessageSendFailedError(OAuthException):
    """Autogenerated exception class for API error code 1100"""
    error_code = 1100
    error_id = "LIVEMESSAGE_SEND_FAILED"
    error_description = 'An error occurred while sending the LiveMessage.'

class LivemessageEventNameTooLongError(OAuthException):
    """Autogenerated exception class for API error code 1101"""
    error_code = 1101
    error_id = "LIVEMESSAGE_EVENT_NAME_TOO_LONG"
    error_description = 'The event_name parameter must be no longer than 128 bytes.'

class LivemessageMessageTooLongError(OAuthException):
    """Autogenerated exception class for API error code 1102"""
    error_code = 1102
    error_id = "LIVEMESSAGE_MESSAGE_TOO_LONG"
    error_description = 'The message parameter must be no longer than 1024 bytes.'

class ChatSendFailedError(OAuthException):
    """Autogenerated exception class for API error code 1200"""
    error_code = 1200
    error_id = "CHAT_SEND_FAILED"
    error_description = 'An error occurred while sending the message.'

class PagesCreateError(OAuthException):
    """Autogenerated exception class for API error code 1201"""
    error_code = 1201
    error_id = "PAGES_CREATE"
    error_description = 'You have created too many pages'

class ShareBadUrlError(OAuthException):
    """Autogenerated exception class for API error code 1500"""
    error_code = 1500
    error_id = "SHARE_BAD_URL"
    error_description = 'The url you supplied is invalid'

class NoteCannotModifyError(OAuthException):
    """Autogenerated exception class for API error code 1600"""
    error_code = 1600
    error_id = "NOTE_CANNOT_MODIFY"
    error_description = 'The user does not have permission to modify this note.'

class CommentsUnknownError(OAuthException):
    """Autogenerated exception class for API error code 1700"""
    error_code = 1700
    error_id = "COMMENTS_UNKNOWN"
    error_description = 'An unknown error has occurred.'

class CommentsPostTooLongError(OAuthException):
    """Autogenerated exception class for API error code 1701"""
    error_code = 1701
    error_id = "COMMENTS_POST_TOO_LONG"
    error_description = 'The specified post was too long.'

class CommentsDbDownError(OAuthException):
    """Autogenerated exception class for API error code 1702"""
    error_code = 1702
    error_id = "COMMENTS_DB_DOWN"
    error_description = 'The comments database is down.'

class CommentsInvalidXidError(OAuthException):
    """Autogenerated exception class for API error code 1703"""
    error_code = 1703
    error_id = "COMMENTS_INVALID_XID"
    error_description = 'The specified xid is not valid. xids can only contain letters, numbers, and underscores'

class CommentsInvalidUidError(OAuthException):
    """Autogenerated exception class for API error code 1704"""
    error_code = 1704
    error_id = "COMMENTS_INVALID_UID"
    error_description = 'The specified user is not a user of this application'

class CommentsInvalidPostError(OAuthException):
    """Autogenerated exception class for API error code 1705"""
    error_code = 1705
    error_id = "COMMENTS_INVALID_POST"
    error_description = 'There was an error during posting.'

class CommentsInvalidRemoveError(OAuthException):
    """Autogenerated exception class for API error code 1706"""
    error_code = 1706
    error_id = "COMMENTS_INVALID_REMOVE"
    error_description = 'While attempting to remove the post.'

